### PR TITLE
Exporting class as a single method so that it can be stubbed in the tests.

### PR DESCRIPTION
**Pull request by usman-bajwa**
PDFs are an important part of the Assessments module. To make sure that the process of generating PDFs is working flawlessly, we need to have the unit tests. For tests to work, we need to have a class method that can be stubbed. So in this PR, exporting the class as one main method so that it can be stubbed in the unit tests.

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
@usman-bajwa but it's already exporting the method.
When you require it somewhere i.e `var x = require('index.js')` here `x` would be `function wkhtmltopdf `

Am I right? And than you can stub the `x`

**Comment by usman-bajwa** [comment]
@WaleedAshraf so normally we stub a method in following way:
```javascript
sinon.stub(module, methodName, customFunction)
```
Now without explicitly exporting the main method, how can i stub it?
```javascript
sinon.stub(wkhtmltopdf, fill_in_the_bank, customFunction)
```

**Comment by WaleedAshraf** [comment]
ohh yes -_- why does stub need module name -_- open source main kam krny k nuqsanat -_-

you are right.
i have also found this `proxyquire` can do same thing at test side. your choice 👍

**Review by furqan-razzaq — APPROVED** [review]
LGTM

**Pull request merged**
